version: '3.8'

services:
  server:
    build:
      context: ./back
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/app-db?schema=public"
      JWT_SECRET: example-secret-key
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      CLIENT_URL: http://localhost:5173
    restart: always

  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - '5173:5173'

  redis:
    image: redis:7.2
    ports:
      - '6379:6379'

  postgres:
    image: postgres:16.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
