name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        id: convert_repository
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=owner::${OWNER}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image backend
        run: docker build -t ghcr.io/${{ steps.convert_repository.outputs.owner }}/backend:latest ./back

      - name: Push Docker image to GitHub Container Registry (backend)
        run: docker push ghcr.io/${{ steps.convert_repository.outputs.owner }}/backend:latest