name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Run docker compose
        run: docker compose -f "../docker-compose.yml" up -d --build postgres server redis

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman tests
        run: newman run back/test/tests-projet-web.postman_collection.json